### ISSUE TITLE
match quotes

### ISSUE THREAD

**Issue by aric87** [chieakiba/quiz-app#2]
You should make the quotes consistent throughout: 
https://github.com/chieakiba/quiz-app/blob/master/index.html#L7

**Comment by aric87** [comment]
https://github.com/chieakiba/quiz-app/blob/master/index.html#L15

**Comment by aric87** [comment]
https://github.com/chieakiba/quiz-app/blob/master/js/app.js#L53

**Comment by chieakiba** [comment]
Thanks Aric! I fixed them :)
